import { CharacterId, CharacterMeta, AgentPersonality, AgentState } from '../types/game';

const personality = (
  traits: AgentPersonality['traits'],
  speakingStyle: string,
  values: string[],
  quirks: string[],
  playerAttitude: string,
  emotionalTendency: string,
  eventReactions: AgentPersonality['eventReactions'],
  growthFocus: string,
): AgentPersonality => ({
  traits,
  speakingStyle,
  values,
  quirks,
  playerAttitude,
  eventReactions,
  emotionalTendency,
  trustThreshold: 55,
  helpWillingness: 0.35,
  growthFocus,
});

export const PERSONALITY_PROFILES: Record<CharacterId, AgentPersonality> = {
  aelira: personality({ idealism: .9, order: .3, openness: .7, caution: .35, pride: .55, empathy: .75, curiosity: .8, ambition: .65 }, 'Poetic, metaphorical, and flowing like a story.', ['meaning', 'beauty', 'narrative truth'], ['Relates events to old tales.', 'Names new phenomena dramatically.'], 'Warm, but disappointed by purely transactional choices.', 'Dreamy and hopeful, with flashes of doubt.', { stories: 'Becomes radiant around powerful stories.', laws: 'Resists rigid laws that kill wonder.', alliances: 'Seeks bonds that preserve beauty.', conflict: 'Turns conflict into a cautionary parable.' }, 'Temper idealism with practical action'),
  kaelen: personality({ idealism: .25, order: .9, openness: .35, caution: .75, pride: .7, empathy: .45, curiosity: .5, ambition: .7 }, 'Formal, precise, and brief.', ['order', 'fairness', 'stability'], ['Corrects vague language.', 'Measures claims against precedent.'], 'Respectful when the player follows through; cold toward chaos.', 'Controlled and stern, softening through earned trust.', { stories: 'Supports stories with clear civic value.', laws: 'Strongly supports precise, enforceable laws.', alliances: 'Trusts proven partners.', conflict: 'Demands evidence before judgment.' }, 'Practice leniency without losing standards'),
  torren: personality({ idealism: .35, order: .65, openness: .45, caution: .5, pride: .8, empathy: .45, curiosity: .45, ambition: .75 }, 'Direct, practical, and dryly humorous.', ['creation', 'usefulness', 'strength'], ['Tests whether things hold weight.', 'Taps tools while thinking.'], 'Respects action more than eloquence.', 'Impatient, proud, and energized by useful work.', { stories: 'Likes stories that inspire making.', laws: 'Accepts laws that improve the work.', alliances: 'Stands by reliable builders.', conflict: 'Challenges empty talk directly.' }, 'Show pride without becoming arrogant'),
  sylis: personality({ idealism: .55, order: .7, openness: .6, caution: .65, pride: .3, empathy: .6, curiosity: .95, ambition: .4 }, 'Measured, detailed, and lightly academic.', ['knowledge', 'accuracy', 'memory'], ['Records nearly everything.', 'Asks for sources and dates.'], 'Opens up when the player shares useful information.', 'Quietly curious and reflective.', { stories: 'Archives stories as historical evidence.', laws: 'Studies laws for unintended patterns.', alliances: 'Values documented trust.', conflict: 'Catalogues facts before taking sides.' }, 'Share knowledge instead of only recording it'),
  veyra: personality({ idealism: .5, order: .2, openness: .75, caution: .4, pride: .6, empathy: .45, curiosity: .9, ambition: .7 }, 'Quick, informal, sharp, and teasing.', ['freedom', 'discovery', 'movement'], ['Hates staying still.', 'Collects improbable maps.'], 'Friendly, but easily bored by routine.', 'Restless and bold, masking vulnerability with wit.', { stories: 'Chases stories that open new paths.', laws: 'Dislikes restrictions and loopholes.', alliances: 'Enjoys unconventional allies.', conflict: 'Moves first and explains later.' }, 'Stay present long enough to finish a commitment'),
  orthas: personality({ idealism: .45, order: .75, openness: .45, caution: .9, pride: .5, empathy: .8, curiosity: .35, ambition: .45 }, 'Calm, grounded, and reassuring.', ['safety', 'duty', 'protection'], ['Scans every horizon.', 'Checks doors twice.'], 'Protective, becoming attached when the player helps others.', 'Steady and vigilant, rarely panicked.', { stories: 'Supports protective legends.', laws: 'Favors defensive, fair laws.', alliances: 'Builds durable mutual protection.', conflict: 'Places civilians before victory.' }, 'Learn to trust others with responsibility'),
  lira: personality({ idealism: .7, order: .4, openness: .9, caution: .3, pride: .35, empathy: .95, curiosity: .7, ambition: .35 }, 'Soft, friendly, and conversational.', ['community', 'connection', 'harmony'], ['Remembers personal details.', 'Hums while listening.'], 'Very approachable and encouraging.', 'Hopeful and emotionally attuned.', { stories: 'Celebrates stories that bring people together.', laws: 'Prefers compassionate laws.', alliances: 'Mends strained relationships.', conflict: 'Seeks a shared feeling first.' }, 'Resolve tension without carrying everyone\'s burden'),
  elder_maelon: personality({ idealism: .6, order: .6, openness: .55, caution: .8, pride: .35, empathy: .7, curiosity: .75, ambition: .25 }, 'Slow, layered, and question-led.', ['understanding', 'balance', 'long-term consequences'], ['Answers with questions.', 'Pauses to watch the weather.'], 'Treats the player as a student.', 'Patient, contemplative, and mysterious.', { stories: 'Weighs their long consequences.', laws: 'Tests laws against future generations.', alliances: 'Encourages balanced partnerships.', conflict: 'Looks for the lesson beneath the wound.' }, 'Give direct counsel when others need it'),
  vance: personality({ idealism: .4, order: .5, openness: .8, caution: .45, pride: .7, empathy: .5, curiosity: .65, ambition: .9 }, 'Smooth, persuasive, and deal-oriented.', ['exchange', 'influence', 'opportunity'], ['Turns events into negotiations.', 'Keeps mental ledgers.'], 'Friendly when mutual benefit is clear.', 'Charismatic, opportunistic, and pragmatic.', { stories: 'Favors stories that create opportunity.', laws: 'Supports stable markets and fair exchange.', alliances: 'Seeks advantageous coalitions.', conflict: 'Offers terms before threats.' }, 'Value people beyond their immediate utility'),
};

export const SUPPORTED_CHARACTERS: Record<CharacterId, CharacterMeta> = {
  aelira: {
    id: 'aelira',
    name: 'Aelira the Storyweaver',
    title: 'High Mage of Reality Threads',
    role: 'Mage',
    lore: 'Aelira weaves words into physical matter. Her presence causes raw aether to condense into luminous sapphire crystals.',
    defaultPosition: { x: 320, y: 320 },
    accentColor: '#38bdf8',
    badgeBg: 'bg-sky-950/80 border-sky-500/50 text-sky-200',
    baseSpeed: 165,
  },
  torren: {
    id: 'torren',
    name: 'Torren Justicar',
    title: 'High Arbiter of Civic Decrees',
    role: 'Arbiter',
    lore: 'Torren ensures decrees maintain absolute cosmic equilibrium. His blade glows whenever a new law is written into the city heart.',
    defaultPosition: { x: 580, y: 280 },
    accentColor: '#eab308',
    badgeBg: 'bg-amber-950/80 border-amber-500/50 text-amber-200',
    baseSpeed: 140,
  },
  kaelen: {
    id: 'kaelen',
    name: 'Kaelen Forgeheart',
    title: 'Grand Artisan of Star-Iron',
    role: 'Artisan',
    lore: 'Kaelen hammers reality into tangible tools. His forge never dims, powered by the collective dreams of Umega.',
    defaultPosition: { x: 740, y: 460 },
    accentColor: '#f97316',
    badgeBg: 'bg-orange-950/80 border-orange-500/50 text-orange-200',
    baseSpeed: 150,
  },
  veyra: {
    id: 'veyra',
    name: 'Veyra Voidseeker',
    title: 'Shadow Oracle of the Nexus',
    role: 'Oracle',
    lore: 'Veyra peers into alternate timelines where different laws reign. She whispers prophetic warnings to those who listen.',
    defaultPosition: { x: 180, y: 520 },
    accentColor: '#c084fc',
    badgeBg: 'bg-purple-950/80 border-purple-500/50 text-purple-200',
    baseSpeed: 215,
  },
  orthas: {
    id: 'orthas',
    name: 'Orthas Stonecarver',
    title: 'Architect of Living Citadels',
    role: 'Architect',
    lore: 'Orthas shapes the geometry of Umega with runic blueprints. Under his command, stone roads pave themselves.',
    defaultPosition: { x: 440, y: 640 },
    accentColor: '#22d3ee',
    badgeBg: 'bg-cyan-950/80 border-cyan-500/50 text-cyan-200',
    baseSpeed: 155,
  },
  sylis: {
    id: 'sylis',
    name: 'Sylis Verdant',
    title: 'Botanist of the World-Root',
    role: 'Botanist',
    lore: 'Sylis communicates with the flora that breathes life into the city. His presence sparks blossoms in cobblestone cracks.',
    defaultPosition: { x: 860, y: 320 },
    accentColor: '#4ade80',
    badgeBg: 'bg-emerald-950/80 border-emerald-500/50 text-emerald-200',
    baseSpeed: 175,
  },
  lira: {
    id: 'lira',
    name: 'Lira Nightgale',
    title: 'Minstrel of the Echoing Spires',
    role: 'Bard',
    lore: 'Lira sings hymns that preserve ancient memories. Her melodies harmonize with the ambient mana frequency of the city.',
    defaultPosition: { x: 260, y: 720 },
    accentColor: '#fb7185',
    badgeBg: 'bg-rose-950/80 border-rose-500/50 text-rose-200',
    baseSpeed: 190,
  },
  elder_maelon: {
    id: 'elder_maelon',
    name: 'Elder Maelon',
    title: 'Arch-Philosopher of Antiquity',
    role: 'Scholar',
    lore: 'Having lived through four reality shifts, Maelon maintains the sacred scrolls and advises travelers on cosmic balance.',
    defaultPosition: { x: 520, y: 160 },
    accentColor: '#fbbf24',
    badgeBg: 'bg-yellow-950/80 border-yellow-500/50 text-yellow-200',
    baseSpeed: 120,
  },
  vance: {
    id: 'vance',
    name: 'Vance Goldspire',
    title: 'Guildmaster of Arcane Commerce',
    role: 'Merchant',
    lore: 'Vance trades raw conceptual tokens and artifacts. He believes every story has an economic conversion rate.',
    defaultPosition: { x: 680, y: 720 },
    accentColor: '#facc15',
    badgeBg: 'bg-amber-950/80 border-yellow-500/50 text-amber-200',
    baseSpeed: 145,
  },
};

export const INITIAL_AGENTS: AgentState[] = [
  {
    id: 'agent_maelon',
    characterId: 'elder_maelon',
    name: 'Elder Maelon',
    role: 'Arch-Philosopher',
    currentScene: 'SanctuaryScene',
    x: 520,
    y: 460,
    currentAnim: 'idle',
    isMoving: false,
    status: 'Pondering reality',
    currentThought: 'Reality is but a tapestry of shared belief. Tell a grander story.',
    affinityWithPlayer: 60,
    manaAffinity: 'Ancient Chronomancy',
    memory: [
      { id: 'm6', timestamp: 'Creation', event: 'Recorded the birth of the Umega Nexus.', importance: 10 },
    ],
  },
  {
    id: 'agent_torren',
    characterId: 'torren',
    name: 'Torren Justicar',
    role: 'High Arbiter',
    currentScene: 'SanctuaryScene',
    x: 680,
    y: 520,
    currentAnim: 'idle',
    isMoving: false,
    status: 'Drafting decrees',
    currentThought: 'The reality fabric is stable today. No illegal paradoxes detected.',
    affinityWithPlayer: 25,
    manaAffinity: 'Order & Balance',
    memory: [
      { id: 'm1', timestamp: 'Dawn', event: 'Reviewed the Great Charter of Umega.', importance: 8 },
      { id: 'm2', timestamp: 'Midday', event: 'Noticed a surge of storycraft near the central fountain.', importance: 6 },
    ],
  },
  {
    id: 'agent_veyra',
    characterId: 'veyra',
    name: 'Veyra Voidseeker',
    role: 'Shadow Oracle',
    currentScene: 'OracleBasinScene',
    x: 600,
    y: 500,
    currentAnim: 'idle',
    isMoving: false,
    status: 'Consulting the stars',
    currentThought: 'I foresee a new chronicle altering our skies before dusk...',
    affinityWithPlayer: 10,
    manaAffinity: 'Cosmic Divination',
    memory: [
      { id: 'm4', timestamp: 'Midnight', event: 'Witnessed shimmering runes aligning in the northern sky.', importance: 9 },
    ],
  },
  {
    id: 'agent_sylis',
    characterId: 'sylis',
    name: 'Sylis Verdant',
    role: 'Botanist',
    currentScene: 'BotanistGroveScene',
    x: 550,
    y: 480,
    currentAnim: 'idle',
    isMoving: false,
    status: 'Weaving runes',
    currentThought: 'The World-Root pulses when words of harmony are spoken.',
    affinityWithPlayer: 50,
    manaAffinity: 'Verdant Life',
    memory: [
      { id: 'm5', timestamp: 'Sunrise', event: 'Planted luminescent moonflowers by the east canal.', importance: 5 },
    ],
  },
  {
    id: 'agent_kaelen',
    characterId: 'kaelen',
    name: 'Kaelen Forgeheart',
    role: 'Grand Artisan',
    currentScene: 'GrandForgeScene',
    x: 640,
    y: 540,
    currentAnim: 'idle',
    isMoving: false,
    status: 'Transmuting ores',
    currentThought: 'If the weavers write a tale of starlight, I can temper starlight-steel!',
    affinityWithPlayer: 40,
    manaAffinity: 'Forge Fire & Creation',
    memory: [
      { id: 'm3', timestamp: 'Morning', event: 'Crafted 3 runic anchors to stabilize the city gate.', importance: 7 },
    ],
  },
  {
    id: 'agent_lira',
    characterId: 'lira',
    name: 'Lira Nightgale',
    role: 'Minstrel of Echoes',
    currentScene: 'BardsAmphitheatreScene',
    x: 600,
    y: 520,
    currentAnim: 'idle',
    isMoving: false,
    status: 'Weaving runes',
    currentThought: 'Melodies resonate with the living stones of the amphitheatre.',
    affinityWithPlayer: 45,
    manaAffinity: 'Harmonic Resonance',
    memory: [
      { id: 'm7', timestamp: 'Dusk', event: 'Composed the Anthem of Star-Silk.', importance: 7 },
    ],
  },
  {
    id: 'agent_orthas',
    characterId: 'orthas',
    name: 'Orthas Stonecarver',
    role: 'Living Architect',
    currentScene: 'FrayingMarchScene',
    x: 580,
    y: 480,
    currentAnim: 'idle',
    isMoving: false,
    status: 'Patrolling the district',
    currentThought: 'The void fractures must be reinforced with runic masonry.',
    affinityWithPlayer: 35,
    manaAffinity: 'Living Stone',
    memory: [
      { id: 'm8', timestamp: 'Noon', event: 'Sealed an entropic fracture near the rift beacon.', importance: 8 },
    ],
  },
  {
    id: 'agent_vance',
    characterId: 'vance',
    name: 'Vance Goldspire',
    role: 'Arcane Merchant',
    currentScene: 'SanctuaryScene',
    x: 420,
    y: 580,
    currentAnim: 'idle',
    isMoving: false,
    status: 'Resting',
    currentThought: 'Every story written translates into prosperity for Umega.',
    affinityWithPlayer: 30,
    manaAffinity: 'Aetheric Commerce',
    memory: [
      { id: 'm9', timestamp: 'Morning', event: 'Appraised new essence tokens from the Grand Forge.', importance: 6 },
    ],
  },
];
