import { CharacterId, CharacterMeta, AgentState } from '../types/game';

export const SUPPORTED_CHARACTERS: Record<CharacterId, CharacterMeta> = {
  aelira: {
    id: 'aelira',
    name: 'Aelira the Storyweaver',
    title: 'High Mage of Reality Threads',
    role: 'Mage',
    lore: 'Aelira weaves words into physical matter. Her presence causes raw aether to condense into luminous sapphire crystals.',
    defaultPosition: { x: 320, y: 320 },
    accentColor: '#38bdf8',
    badgeBg: 'bg-sky-950/80 border-sky-500/50 text-sky-200',
  },
  torren: {
    id: 'torren',
    name: 'Torren Justicar',
    title: 'High Arbiter of Civic Decrees',
    role: 'Arbiter',
    lore: 'Torren ensures decrees maintain absolute cosmic equilibrium. His blade glows whenever a new law is written into the city heart.',
    defaultPosition: { x: 580, y: 280 },
    accentColor: '#eab308',
    badgeBg: 'bg-amber-950/80 border-amber-500/50 text-amber-200',
  },
  kaelen: {
    id: 'kaelen',
    name: 'Kaelen Forgeheart',
    title: 'Grand Artisan of Star-Iron',
    role: 'Artisan',
    lore: 'Kaelen hammers reality into tangible tools. His forge never dims, powered by the collective dreams of Umega.',
    defaultPosition: { x: 740, y: 460 },
    accentColor: '#f97316',
    badgeBg: 'bg-orange-950/80 border-orange-500/50 text-orange-200',
  },
  veyra: {
    id: 'veyra',
    name: 'Veyra Voidseeker',
    title: 'Shadow Oracle of the Nexus',
    role: 'Oracle',
    lore: 'Veyra peers into alternate timelines where different laws reign. She whispers prophetic warnings to those who listen.',
    defaultPosition: { x: 180, y: 520 },
    accentColor: '#c084fc',
    badgeBg: 'bg-purple-950/80 border-purple-500/50 text-purple-200',
  },
  orthas: {
    id: 'orthas',
    name: 'Orthas Stonecarver',
    title: 'Architect of Living Citadels',
    role: 'Architect',
    lore: 'Orthas shapes the geometry of Umega with runic blueprints. Under his command, stone roads pave themselves.',
    defaultPosition: { x: 440, y: 640 },
    accentColor: '#22d3ee',
    badgeBg: 'bg-cyan-950/80 border-cyan-500/50 text-cyan-200',
  },
  sylis: {
    id: 'sylis',
    name: 'Sylis Verdant',
    title: 'Botanist of the World-Root',
    role: 'Botanist',
    lore: 'Sylis communicates with the flora that breathes life into the city. His presence sparks blossoms in cobblestone cracks.',
    defaultPosition: { x: 860, y: 320 },
    accentColor: '#4ade80',
    badgeBg: 'bg-emerald-950/80 border-emerald-500/50 text-emerald-200',
  },
  lira: {
    id: 'lira',
    name: 'Lira Nightgale',
    title: 'Minstrel of the Echoing Spires',
    role: 'Bard',
    lore: 'Lira sings hymns that preserve ancient memories. Her melodies harmonize with the ambient mana frequency of the city.',
    defaultPosition: { x: 260, y: 720 },
    accentColor: '#fb7185',
    badgeBg: 'bg-rose-950/80 border-rose-500/50 text-rose-200',
  },
  elder_maelon: {
    id: 'elder_maelon',
    name: 'Elder Maelon',
    title: 'Arch-Philosopher of Antiquity',
    role: 'Scholar',
    lore: 'Having lived through four reality shifts, Maelon maintains the sacred scrolls and advises travelers on cosmic balance.',
    defaultPosition: { x: 520, y: 160 },
    accentColor: '#fbbf24',
    badgeBg: 'bg-yellow-950/80 border-yellow-500/50 text-yellow-200',
  },
  vance: {
    id: 'vance',
    name: 'Vance Goldspire',
    title: 'Guildmaster of Arcane Commerce',
    role: 'Merchant',
    lore: 'Vance trades raw conceptual tokens and artifacts. He believes every story has an economic conversion rate.',
    defaultPosition: { x: 680, y: 720 },
    accentColor: '#facc15',
    badgeBg: 'bg-amber-950/80 border-yellow-500/50 text-amber-200',
  },
};

export const INITIAL_AGENTS: AgentState[] = [
  {
    id: 'agent_maelon',
    characterId: 'elder_maelon',
    name: 'Elder Maelon',
    role: 'Arch-Philosopher',
    currentScene: 'SanctuaryScene',
    x: 520,
    y: 460,
    currentAnim: 'idle',
    isMoving: false,
    status: 'Pondering reality',
    currentThought: 'Reality is but a tapestry of shared belief. Tell a grander story.',
    affinityWithPlayer: 60,
    manaAffinity: 'Ancient Chronomancy',
    memory: [
      { id: 'm6', timestamp: 'Creation', event: 'Recorded the birth of the Umega Nexus.', importance: 10 },
    ],
  },
  {
    id: 'agent_torren',
    characterId: 'torren',
    name: 'Torren Justicar',
    role: 'High Arbiter',
    currentScene: 'SanctuaryScene',
    x: 680,
    y: 520,
    currentAnim: 'idle',
    isMoving: false,
    status: 'Drafting decrees',
    currentThought: 'The reality fabric is stable today. No illegal paradoxes detected.',
    affinityWithPlayer: 25,
    manaAffinity: 'Order & Balance',
    memory: [
      { id: 'm1', timestamp: 'Dawn', event: 'Reviewed the Great Charter of Umega.', importance: 8 },
      { id: 'm2', timestamp: 'Midday', event: 'Noticed a surge of storycraft near the central fountain.', importance: 6 },
    ],
  },
  {
    id: 'agent_veyra',
    characterId: 'veyra',
    name: 'Veyra Voidseeker',
    role: 'Shadow Oracle',
    currentScene: 'OracleBasinScene',
    x: 600,
    y: 500,
    currentAnim: 'idle',
    isMoving: false,
    status: 'Consulting the stars',
    currentThought: 'I foresee a new chronicle altering our skies before dusk...',
    affinityWithPlayer: 10,
    manaAffinity: 'Cosmic Divination',
    memory: [
      { id: 'm4', timestamp: 'Midnight', event: 'Witnessed shimmering runes aligning in the northern sky.', importance: 9 },
    ],
  },
  {
    id: 'agent_sylis',
    characterId: 'sylis',
    name: 'Sylis Verdant',
    role: 'Botanist',
    currentScene: 'BotanistGroveScene',
    x: 550,
    y: 480,
    currentAnim: 'idle',
    isMoving: false,
    status: 'Weaving runes',
    currentThought: 'The World-Root pulses when words of harmony are spoken.',
    affinityWithPlayer: 50,
    manaAffinity: 'Verdant Life',
    memory: [
      { id: 'm5', timestamp: 'Sunrise', event: 'Planted luminescent moonflowers by the east canal.', importance: 5 },
    ],
  },
  {
    id: 'agent_kaelen',
    characterId: 'kaelen',
    name: 'Kaelen Forgeheart',
    role: 'Grand Artisan',
    currentScene: 'GrandForgeScene',
    x: 640,
    y: 540,
    currentAnim: 'idle',
    isMoving: false,
    status: 'Transmuting ores',
    currentThought: 'If the weavers write a tale of starlight, I can temper starlight-steel!',
    affinityWithPlayer: 40,
    manaAffinity: 'Forge Fire & Creation',
    memory: [
      { id: 'm3', timestamp: 'Morning', event: 'Crafted 3 runic anchors to stabilize the city gate.', importance: 7 },
    ],
  },
  {
    id: 'agent_lira',
    characterId: 'lira',
    name: 'Lira Nightgale',
    role: 'Minstrel of Echoes',
    currentScene: 'BardsAmphitheatreScene',
    x: 600,
    y: 520,
    currentAnim: 'idle',
    isMoving: false,
    status: 'Weaving runes',
    currentThought: 'Melodies resonate with the living stones of the amphitheatre.',
    affinityWithPlayer: 45,
    manaAffinity: 'Harmonic Resonance',
    memory: [
      { id: 'm7', timestamp: 'Dusk', event: 'Composed the Anthem of Star-Silk.', importance: 7 },
    ],
  },
  {
    id: 'agent_orthas',
    characterId: 'orthas',
    name: 'Orthas Stonecarver',
    role: 'Living Architect',
    currentScene: 'FrayingMarchScene',
    x: 580,
    y: 480,
    currentAnim: 'idle',
    isMoving: false,
    status: 'Patrolling the district',
    currentThought: 'The void fractures must be reinforced with runic masonry.',
    affinityWithPlayer: 35,
    manaAffinity: 'Living Stone',
    memory: [
      { id: 'm8', timestamp: 'Noon', event: 'Sealed an entropic fracture near the rift beacon.', importance: 8 },
    ],
  },
  {
    id: 'agent_vance',
    characterId: 'vance',
    name: 'Vance Goldspire',
    role: 'Arcane Merchant',
    currentScene: 'SanctuaryScene',
    x: 420,
    y: 580,
    currentAnim: 'idle',
    isMoving: false,
    status: 'Resting',
    currentThought: 'Every story written translates into prosperity for Umega.',
    affinityWithPlayer: 30,
    manaAffinity: 'Aetheric Commerce',
    memory: [
      { id: 'm9', timestamp: 'Morning', event: 'Appraised new essence tokens from the Grand Forge.', importance: 6 },
    ],
  },
];
